"""tkxlib.kbinput の型スタブ。"""


def _row_list(value: str) -> list[str]: ...

def get_int(prompt: str = "int>") -> int: ...

def get_float(prompt: str = "float>") -> float: ...

def get_str(prompt: str = "str>") -> str: ...

def get_bool(prompt: str = "bool>") -> bool | None: ...

def get_list(prompt: str = "CSV>") -> list[str]: ...

def get_list_int(prompt: str = "CSV>") -> list[int]: ...

def get_list_float(prompt: str = "CSV>") -> list[float]: ...

def get_tuple(prompt: str = "CSV>") -> tuple[str, ...]: ...

def get_tuple_int(prompt: str = "CSV>") -> tuple[int, ...]: ...

def get_tuple_float(prompt: str = "CSV>") -> tuple[float, ...]: ...

def get_set(prompt: str = "CSV>") -> set[str]: ...

def get_set_int(prompt: str = "CSV>") -> set[int]: ...

def get_set_float(prompt: str = "CSV>") -> set[float]: ...

def get_dict(prompt: str = "CSV (k:v)>") -> dict[str, str]: ...

def get_dict_int(prompt: str = "CSV (k:v)>") -> dict[str, int]: ...

def get_dict_float(prompt: str = "CSV (k:v)>") -> dict[str, float]: ...

def get_coordinate(prompt: str = "x, y > ") -> tuple[float, float]: ...
